name: CI

on: [pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  android:
    runs-on: macos-14-xlarge
    timeout-minutes: 10
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Run CI
        run: bash ./scripts/run_ci_tasks.sh -a
  ios:
    runs-on: macos-14-xlarge
    timeout-minutes: 10
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Run CI
        run: bash ./scripts/run_ci_tasks.sh -i
