name: CI

on: [pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  android:
    runs-on: macos-15-xlarge
    timeout-minutes: 10
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer
    steps:
      - name: Install Android Build Tools
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"
      - uses: actions/checkout@v4
      - name: Run CI
        run: bash ./scripts/run_ci_tasks.sh -a
  ios:
    runs-on: macos-15-xlarge
    timeout-minutes: 10
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Run CI
        run: bash ./scripts/run_ci_tasks.sh -i
