name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-26-xlarge
    timeout-minutes: 25

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Version
        run: bash ./scripts/check_version.sh ${GITHUB_REF/refs\/tags\//}
      - name: Install Android Build Tools
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"
      - name: Run CI
        run: |
          bash ./scripts/run_ci_tasks.sh -a -i

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Get the release notes
        id: get_release_notes
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          delimiter="$(openssl rand -hex 8)"
          {
            echo "NOTES<<${delimiter}"
            awk "/## Version $VERSION/{flag=1;next}/## Version/{flag=0}flag" CHANGELOG.md
            echo "${delimiter}"
          } >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: Publish modules
        run: |
          cd cordova-airship/
          npm publish --access public
          cd -
          cd cordova-airship-hms/
          npm publish --access public
          cd -

      - name: Github Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: ${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.get_release_notes.outputs.NOTES }}
          draft: false
          prerelease: false

  publish-docs:
    needs: [deploy]
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/publish-docs.yml
    with:
      version: ${{ github.ref_name }}
    secrets: inherit

  notify-release:
    needs: [build, deploy, publish-docs]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: lazy-actions/slatify@master
        with:
          type: ${{ (contains(needs.*.result, 'failure') && 'failure') || (contains(needs.*.result, 'cancelled') && 'cancelled') || 'success' }}
          job_name: "Cordova Release"
          url: ${{ secrets.SLACK_WEBHOOK }}
